### PR TITLE
Setup/setup basic styling

### PR DESCRIPTION
**Pull request by hshahwan**
relate #5 
 - setup font family for titles and body. 
- add common colors for the app, that will help us in the styled components.

### CODE REVIEW

**Review by ali-7 — APPROVED** [review]

**Review by teenie-quaggard — COMMENTED** [review]
One question on the package.json - > didn't we move the eslint to the dependencies because of deployment issues?

**Comment by ali-7** [comment]
@teenie-quaggard 
> One question on the package.json - > didn't we move the eslint to the dependencies because of deployment issues?

yes, eslint plugin that gives the problem, so i moved all the devDep to dep, but travis made an erro coz eslint library is a devDep >>> `eslint-plugin-import`, `eslint-plugin-jsx-a11y`

**Review by teenie-quaggard — APPROVED** [review]
Ok, I understand. Happy for these to be merged.

**Review by Oliversw — APPROVED** [review]
Looks great, love the SVGs. Thanks!

**Pull request merged**
