### PR TITLE
Feature/header component

### PR DESCRIPTION
**Pull request by ali-7**
Relates #28 

* contains a logo that links to home page
* contains hamburger menu
* contains title section

### CODE REVIEW

**Review by teenie-quaggard — COMMENTED** [review]
Thank you for renaming my files 👍

One question - what's with the css file?
client/src/index.css

**Comment by ali-7** [comment]
> Thank you for renaming my files 
> 
> One question - what's with the css file?
> client/src/index.css

@teenie-quaggard for the default configuration of the page, like html, body, general selector tags

**Review by teenie-quaggard — COMMENTED** [review]
Ah ok, there is also something called createGlobalStyle from the styled-components library so that we only use styled-components instead of mixing css & styled-components. Same thing, but maybe a bit cleaner. What do you think?

https://www.youtube.com/watch?v=DL4HAKo76Cw

I'm happy either way, just in case you didn't know about it already :)

**Comment by teenie-quaggard** [comment]
one last thing - i fetched your branch and tried to run it locally, but I get this error:
not sure, but it might be because it says 'fortawesome' instead of 'fontawesome'?

Screen Shot 2019-04-17 at 21 16 54

**Review by ali-7 — COMMENTED** [review]
@teenie-quaggard did u `cd client` and `npm i`?
it's correct.

**Comment by hshahwan** [comment]
@teenie-quaggard  I fetch the branch, it's work.. just you need to npm i command in the client root as Ali said

**Comment by Oliversw** [comment]
> Ah ok, there is also something called createGlobalStyle from the styled-components library so that we only use styled-components instead of mixing css & styled-components. Same thing, but maybe a bit cleaner. What do you think?
> 
> https://www.youtube.com/watch?v=DL4HAKo76Cw
> 
> I'm happy either way, just in case you didn't know about it already :)

Oh this sounds really interesting! Should we make it an issue to refactor later?

**Review by teenie-quaggard — APPROVED** [review]

**Pull request merged**
