### PR TITLE
Feature/tests

### PR DESCRIPTION
**Pull request by charlielafosse**
Hello! :leaves: 

So this proved to be a little trickier than I thought it would've been, but what we've now got is:

1. A unit test for the `About` component that just checks that it renders (lol)

2. Some unit and integration tests for the `Method` and `MethodCard` components

I hope it's something you can build off (if you have time!) and it was super interesting for me, so thank you for letting me tinker! I used [react-testing-library](https://testing-library.com/) which was really helpful for finding and selecting things in a kind of virtual DOM. The existing tests check for different effects upon the remaining resource points when a certain resource is selected.

With the way it's currently set up, you can create more `consts` for each method card's 'Use this resource' checkbox like so: 

`const networkMapCheckbox = getAllByTestId('Network map')[0];`

And that test ID ('Network map') is now being passed from the `cardTitle` value in your `data/methodCardData.js`, down as a prop through `Method` and eventually landing as a unique `data-testid` attribute on the checkbox `input` for each `MethodCard` component that's rendered. You could theoretically chain together lots of `fireEvent.click`s on the different checkboxes and test that the remaining resource points are correct.

Relates #115

### CODE REVIEW

**Comment by ali-7** [comment]
@charlielafosse thank you very much :smiley: 

I just want to ask why you remove the quotes from the .eslintrc.js file ?!

**Comment by charlielafosse** [comment]
Hey @ali-7 I think that's something to do with my linter settings? It was going crazy with the double quotes/single quotes/no quotes

**Comment by charlielafosse** [comment]
@ali-7 I'll change it back now :+1:

**Comment by charlielafosse** [comment]
Also, do you know if it makes a difference with or without quotes? I know that there's a `JSON` standard that requires double quotes on the properties/key names of JSON objects, but I'm not sure about general objects :thinking:

**Comment by ali-7** [comment]
> Also, do you know if it makes a difference with or without quotes? I know that there's a `JSON` standard that requires double quotes on the properties/key names of JSON objects, but I'm not sure about general objects

@charlielafosse it will not make any difference, but I get the config on how to, from the eslint config docs, and saw some examples that use double quotes also in the `js` config, like they want to be consistent with `JSON` standard in `js` files. so that why I ask if there some reason to change it :joy:

**Comment by ali-7** [comment]
@charlielafosse seems like the tests fail after the last pull?

**Comment by charlielafosse** [comment]
@ali-7 taking a look now :mag:

**Comment by charlielafosse** [comment]
@ali-7 fixed in f78afd5  and tests now passing :sunflower:

**Review by ali-7 — APPROVED** [review]
Looks Great, thank you!

**Comment by Oliversw** [comment]
Thank you so much Charlie!!

**Comment by hshahwan** [comment]
Thanks @charlielafosse ! :)

**Review by hshahwan — APPROVED** [review]

**Pull request merged**
